services:
  - type: web
    name: paintworks-backend
     runtime: java
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/paintworks-1.0.0.jar"
    branch: master
    plan: free
